pjt_6/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
    
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

pjt_6/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    # READ1 (전체 영화 목록 페이지 조회)
    path('', views.index, name='index'),
    # READ2 (단일 영화 목록 페이지 조회)
    path('<int:pk>/', views.detail, name='detail'),

    # CREATE(새로운 영화 생성 페이지 조회 & 단일 영화 데이터 저장)
    path('create/', views.create, name='create'),

    # DELETE (단일 영화 데이터 삭제)
    path('<int:pk>/delete/', views.delete, name='delete'),

    # UPDATE (기존 영화 수정 페이지 조회 & 단일 영화 데이터 수정)
    path('<int:pk>/update/', views.update, name='update'),


    # Comment CREATE (댓글 생성)
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),

    # Comment DELETE (댓글 삭제)
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

pjt_6/pjt_6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjt_6/accounts/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser # 상속받을 AbstractUser import

# Create your models here.
class User(AbstractUser):
    pass

pjt_6/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self',    
        on_delete=models.CASCADE,
        null = True,
        related_name = 'replies',
    )

    def __str__(self):
        return self.content

pjt_6/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)
        
# get_user_model 함수는 settings.py에 설정한 AUTH_USER_MODEL의 값 (즉, accounts.User)를 참조한다.

pjt_6/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_safe, require_http_methods

from .models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index') 
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index') 
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)

@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index') 
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    User = get_user_model() # get_user_model()로 활성화되어 있는 User 모델을 가져온다. 
    person = User.objects.get(username=username) # 인자로 넘어온 username으로 User 인스턴스를 person에 할당한다. 
    context = {'person': person}
    return render(request, 'accounts/profile.html', context)

@require_http_methods(['POST'])
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk) # 클릭하여 선택한 유저정보를 person에 담는다. 
        # 만약 선택한 유저정보가 나 자신이라면 follow 가 되면 안됨. 선택한 유저가 나 자신과 다를 때에서만 로직 구동.
        if person != request.user: 
            if person.followers.filter(pk=request.user.pk).exists(): # 선택한 유저를 팔로우한 사람들 중 내가 있다면, 
            # if request.user in person.followers.all() 
                person.followers.remove(request.user)                # followers 목록에서 나를 지운다. 
            else:                                                    # 선택한 유저플 팔로우한 사람들 중 내가 없다면,
                person.followers.add(request.user)                   # followers 목록에 나를 추가한다.
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

pjt_6/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}  
    {{form.as_p}}
    <input type="submit" value="비밀번호 변경">
  </form>
  <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

pjt_6/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {{form.as_p}} 
      <input type="submit" value="로그인">
  </form>
{% endblock content %}

pjt_6/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1> {{person.username}} 님의 프로필</h1>
  <div>
    <p>팔로잉: {{person.followings.all|length}}</p>
    <!--{{person.followings.count}} -->
    <p>팔로워: {{person.followers.all|length}}</p>
    <!--{{person.followers.count}} -->
    <form action="{% url 'accounts:follow' person.pk%}" method='POST'>
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <button type='submit' class='btn btn-danger'>Unfollow</button>
      {% else %}
        <button type='submit' class='btn btn-success'>Follow</button>
      {% endif %}
    </form>
  </div>
  <hr>

  <h2> {{person.username}}'s 게시물</h2>
  {% for movie in person.movie_set.all  %}
    <!--부트스트랩 card-->
    <div class="card"> 
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.content}}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">
          자세히 보기
        </a>
      </div>
    </div>
  {% endfor %}
  <hr><br><br>
  <h5>{{ person.username }}님이 좋아한 게시글</h5>
  {% for movie in person.like_movies.all %}
    <div>{{movie.title}}</div>
  {% endfor %}
  <hr>
  <a href="{% url 'movies:index' %}" class="btn btn-success">뒤로가기</a>

{% endblock  %}

pjt_6/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}  
    {{form.as_p}}
    <input type="submit" value="회원가입">
  </form>
  <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

pjt_6/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {{form.as_p}} 
      <input type="submit" value="수정하기">
  </form>
{% endblock content %}