pjt_6/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    # READ1 (전체 영화 목록 페이지 조회)
    path('', views.index, name='index'),
    # READ2 (단일 영화 목록 페이지 조회)
    path('<int:pk>/', views.detail, name='detail'),

    # CREATE(새로운 영화 생성 페이지 조회 & 단일 영화 데이터 저장)
    path('create/', views.create, name='create'),

    # DELETE (단일 영화 데이터 삭제)
    path('<int:pk>/delete/', views.delete, name='delete'),

    # UPDATE (기존 영화 수정 페이지 조회 & 단일 영화 데이터 수정)
    path('<int:pk>/update/', views.update, name='update'),


    # Comment CREATE (댓글 생성)
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),

    # Comment DELETE (댓글 삭제)
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

pjt_6/pjt_6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjt_6/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self',    
        on_delete=models.CASCADE,
        null = True,
        related_name = 'replies',
    )

    def __str__(self):
        return self.content

pjt_6/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta: 
        model = Movie # Movie Model을 참고
        exclude = ('user', )

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content', )

pjt_6/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
# yj added
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from django.contrib.auth.decorators import login_required  
# Create your views here.

# READ All Movies (전체 영화 데이터 조회 및 index.html 렌더링)
@require_safe
def index(request):
    movies_list = Movie.objects.all() 
    context = {
        'movies_list': movies_list,
    }
    return render(request, 'movies/index.html', context)

# Read One Movies (단일 영화 데이터 조회 및 detail.html 렌더링)
@require_safe
def detail(request, pk):
    movies = Movie.objects.get(id=pk)
    comment_form = CommentForm()
    comments = movies.comment_set.all()
    re_comment_list = movies.comment_set.filter(parent__isnull=True) # 대댓글 리스트
    context = {
        'movies': movies,
        'comment_form': comment_form,
        'comments': comments,
        're_comment_list': re_comment_list,
    }
    return render(request, 'movies/detail.html', context) 

# CREATE (Create.html)
@require_http_methods(['GET', 'POST'])
@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES) # user가 입력한 데이터를 form에 채운다.
        if form.is_valid():                # 유효성 검사를 통과하면 
            movies = form.save(commit=False)        # 데이터 저장 후 
            movies.user = request.user
            movies.save()
            return redirect('movies:detail', movies.pk) # 상세 페이지로 redirect
    else:
        form = MovieForm()             # 비어있는 form을 만든다.
        
    context = {'form': form}
    return render(request, 'movies/create.html', context) # 유효성 검사를 통과하지 못하면 작성 페이지로 redirect

# DELETE (단일 영화 데이터 삭제 및 index.html 리다이렉트)
@require_POST
@login_required
def delete(request, pk):
    movies = Movie.objects.get(id=pk)
    if request.method == 'POST':
        movies.delete()
        return redirect('movies:index')
    else:
        redirect('movies:detail', movies.pk)

# UPDATE (수정 대상 영화 데이터 조회 및 update.html 렌더링)
@require_http_methods(['GET', 'POST'])
@login_required
def update(request, pk):
    movies = Movie.objects.get(id=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance = movies) # instance 인자로 수정 대상이 되는 객체를 지정
        if form.is_valid(): # 유효성 검사를 통과하면
            form.save()     # 데이터 저장
            return redirect('movies:detail', pk=movies.pk)
    else:
        form = MovieForm(instance=movies) # 기존 Movies 데이터를 채운 form

    context = {'movies': movies, 'form': form,}
    return render(request, 'movies/update.html', context)

@require_POST
@login_required
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        parent_pk = request.POST.get('parent_pk')
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            if parent_pk: # 답글
                parent_comment = Comment.objects.get(pk=parent_pk)
                comment.parent = parent_comment
            comment.save()
        return redirect('movies:detail', movie.pk)
    return redirect('accounts:login')

@require_POST
@login_required
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk = comment_pk)
        if request.user == comment.user:
            comment.delete()    
        return redirect('movies:detail', movie_pk)
    return redirect('accounts:login')

pjt_6/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>새로운 영화를 등록하세요</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
  </form>

  <a href="{% url 'movies:index' %}">전체 영화 목록 조회 페이지로 돌아가기</a>
{% endblock content %}

pjt_6/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>영화 상세 정보 페이지</h1>
  <hr>

  {% if movies.poster_url %}
    <img src="{{movies.poster_url}}" alt="">
  {% endif %}

  <p>영화 제목 : {{movies.title}}</p>
  <p>평점 : {{movies.score}}</p>
  <p>관객 수 : {{movies.audience}}</p>
  <p>개봉일 : {{movies.release_date}}</p>
  <p>장르 : {{movies.genre}}</p>
  <p>영화소개 : {{movies.description}}</p>
  {% if movies.actor_image %}
    <p>대표 배우</p>
    <img src="{{movies.actor_image.url}}" alt="" width=100>
  {% endif %}

  {% comment %} 수정 {% endcomment %}
  <a href="{% url 'movies:update' movies.pk %}">EDIT</a>

  {% comment %} 삭제 {% endcomment %}
  <form action="{% url 'movies:delete' movies.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>

  <br>
  {% comment %} 댓글 {% endcomment %}
  <h5>댓글<h5>
  <form action="{% url 'movies:comments_create' movies.pk %}" method="POST">
    {% csrf_token %}
    {{comment_form}}
    <input type="submit" value="작성">
  </form>
  <hr>
  <h5>댓글 목록<h5>
  <ul>
    {% for comment in comments %}
      <li>
        {{comment.content}} - {{comment.user}}
        {% if request.user == comment.user %}
        <form action="{% url 'movies:comments_delete' movies.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제">
        </form>
        {% endif %}
      </li>

      {% for reply in comment.replies.all %}
        <p> >> {{reply.content}} </p>
      {% endfor %}

      <form action="{% url 'movies:comments_create' movies.pk %}" method="POST">
        <input type="hidden" name="parent_pk" value="{{ comment.pk }}">
          {% csrf_token %}
          {{comment_form}} 
        <input type="submit" value="대댓글">
      </form>

    {% endfor %}
  </ul>
  <hr>
  <a href="{% url 'movies:index' %}">전체 영화 목록 조회 페이지로 돌아가기</a>
{% endblock content %}

pjt_6/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>전체 영화 목록 조회 페이지</h1>
  <hr>
  {% for movies in movies_list %}
    <p>영화 번호: {{movies.pk}}</p>
    <p>
      <a href="{% url 'movies:detail' movies.pk %}">
      영화 제목: {{movies.title}}</a>
    </p>
    <p>영화 평점: {{movies.score}}</p>
  {% endfor %}

  <a href="{% url 'movies:create' %}">여기를 눌러 새로운 글을 작성하세요</a>
{% endblock content %}

pjt_6/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>

    <form action="{% url 'movies:update' movies.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="reset" value="reset">
      <input type="submit">
    </form>

  <hr>
  <a href="{% url 'movies:index' %}">목록보기</a>
  <br>
  <a href="{% url 'movies:detail' movies.pk %}">뒤로 돌아가기</a>
{% endblock content %}